### ISSUE TITLE
can I use this library on ios7?

### ISSUE THREAD

**Issue by shuoli84** [kzaher/RxSwift#69] opened 2015-07-27 03:20 UTC
Any known issue? Thanks. 
I can't find an answer in readme.md and google.

**Comment by kzaher** [comment] 2015-07-27 07:12
Hi,
you actually can. I'll document this. But you'll need to manually copy the files to project and if you are using RxCocoa find replace all `import RxSwift` to `` because there is no RxSwift module if you copy the files.

I'm in the process of massive update to documentation, but yeah, some of the people have done that and they say it works for them.

The problem is that iOS 7 doesn't support dynamic frameworks

**Comment by shuoli84** [comment] 2015-07-27 07:43
Good to know. Thanks.

**Comment by shuoli84** [comment] 2015-07-27 07:48
I met a crash on ios7.1 in simulator. Not sure why. Any idea? 
![screen shot 2015-07-27 at 3 47 36 pm](https://cloud.githubusercontent.com/assets/3402035/8900905/e3787da8-3476-11e5-993b-fec23ff3b6cd.png)

**Comment by shuoli84** [comment] 2015-07-27 07:51
```
(lldb) po self.throttleState.cancellable
0x00007fb0605ce770
 {
  CaiShuo.DisposeBase = {}
  lock = (_lock = 0)
  state = {
    current = nil
    disposed = false
  }
}

po d
CaiShuo.SingleAssignmentDisposable
```

**Comment by kzaher** [comment] 2015-07-27 07:53
Hm, never seen this before.

I'm hoping this isn't swift compiler striking again :(

Can you maybe share the code snippet that caused this? What version of Xcode are you using?

**Comment by shuoli84** [comment] 2015-07-27 07:54
Xcode 6.4
```swift
        let chartTypeObservable = Variable(chartType as Observable<ChartType>)
            >- switchLatest
            >- throttle(0.3, MainScheduler.sharedInstance)
            >- distinctUntilChanged
        
        combineLatest(chartTypeObservable, stock) {(type:$0, stock:$1)}
            >- map { [unowned self] item -> Observable<ChartDrawType> in
                if item.type == .Minute || item.type == .FiveDays {
                    return self.getMinutesChartData(item.stock!.id, type: item.type)
                }
                else {
                    return self.getCandleChartData(item.stock!.id, type: item.type)
                }
            }
            >- switchLatest
            >- subscribeNext {[unowned self] item in
                switch item {
                case .Minute(let type, let data):
                    if type == .Minute {
                        self.minutesData.next(data)
                    }
                    else {
                        self.fiveDaysData.next(data)
                    }
                case .Candle(let type, let data):
                    switch type {
                    case .DailyCandle:
                        self.dailyCandleData.next(data)
                    case .WeeklyCandle:
                        self.weeklyCandleData.next(data)
                    case .MonthlyCandle:
                        self.monthlyCandleData.next(data)
                    default:
                        break        
                    }
                default:
                    break
                }
                
            }
            >- disposeBag.addDisposable
```

**Comment by kzaher** [comment] 2015-07-27 08:10
Hm, the only weird thing that comes to my mind is 

```
let chartTypeObservable = Variable(chartType as Observable<ChartType>)
            >- switchLatest
            >- throttle(0.3, MainScheduler.sharedInstance)
            >- distinctUntilChanged
```

You probably meant to say

```
let chartTypeObservable = chartType
            >- throttle(0.3, MainScheduler.sharedInstance)
            >- distinctUntilChanged
```
?

I mean it shouldn't crash the app in any way, but I'm just trying to narrow down the problem.

**Comment by shuoli84** [comment] 2015-07-27 08:12
Sounds like arc issue. I rerun the application and it crashed on somewhere else. 
![screen shot 2015-07-27 at 4 04 29 pm](https://cloud.githubusercontent.com/assets/3402035/8901281/3d3b0880-347a-11e5-8028-3b92d22cc8ea.png)

**Comment by shuoli84** [comment] 2015-07-27 08:19
If I removed the throttle(0.3) line of code, it works fine.

**Comment by kzaher** [comment] 2015-07-27 08:33
Hm, that is extremely weird behavior. 

It looks to me like this could be some kind of compiler or arc bug, but it's hard to tell.

I have made tests to ensure that arc does retain function arguments

```
var deallocated = false
var realTest: Anything? = nil

func clearRealTest() {
    realTest = nil
}


class Anything {
    var elements = [Int]()
    
    func justCallIt(action: () -> Void) {
        clearRealTest()
        action()
    }
    
    deinit {
        deallocated = true
    }
}

// http://lists.apple.com/archives/objc-language/2011/Nov/msg00005.html
// but you never know :)
func testFunctionCallRetainsArguments() {
    
    // first check is dealloc method working
    
    var a: Anything? = Anything()
    
    assert(!deallocated)
    a = nil
    assert(deallocated)
    
    // then check unsafe
    
    deallocated = false
    
    realTest = Anything()
    
    assert(!deallocated)
    
    realTest?.justCallIt {
        assert(!deallocated)
        realTest = nil
        assert(!deallocated)
    }
    assert(deallocated)
}
``` 
And docs do suggest that it does
http://lists.apple.com/archives/objc-language/2011/Nov/msg00005.html

When I run them on ios 7 simulator, they do pass.

Hot sure how this can be happening. If you could help me maybe pinpoint the problem, I would really appreciate it. I would really like to get to the bottom of this since this could potentially affect general Rx code.

You could try maybe turning on zombie objects in debugger to crash the app closer to source of the crash if it's arc/corruption issue.

You could also maybe play with the code in `class Throttle_<O: ObserverType, SchedulerType: Scheduler>.on`.

Any help is appreciated.

**Comment by shuoli84** [comment] 2015-07-27 08:40
I am trying hard to find the root cause too. I'll post you if any update.

**Comment by kzaher** [comment] 2015-07-27 08:41
:+1:

**Comment by shuoli84** [comment] 2015-07-27 09:08
revoke 
```
If I removed the throttle(0.3) line of code, it works fine. 
```
Still has problem.

**Comment by kzaher** [comment] 2015-07-27 12:00
I've done this

```
struct Stock {
    let id: String?
}

enum ChartType {
    case Minute
    case FiveDays
}

enum ChartDrawType {
    case A
}

class ViewController: UIViewController {
    

    
    override func viewDidLoad() {
        super.viewDidLoad()
    
        var stock = Variable(Stock(id: ""))
    
        var chartType = Variable<ChartType>(.Minute)
        
        let disposeBag = DisposeBag()
        
        let chartTypeObservable = Variable(chartType as Observable<ChartType>)
            >- switchLatest
            >- throttle(0.3, MainScheduler.sharedInstance)
            >- distinctUntilChanged
        
        combineLatest(chartTypeObservable, stock) {(type:$0, stock:$1)}
            >- map { [unowned self] item -> Observable<ChartDrawType> in
                return just(ChartDrawType.A)
            }
            >- switchLatest
            >- subscribeNext {[unowned self] item in
                println(item)
            }
            >- disposeBag.addDisposable
    }
```

And it doesn't crash for me.
I was using CocoaPods and RxSwift 1.8.1, Xcode 6.4, iOS 7.1 simulator.

If I could find a way to repro this on my computer, I could investigate this.

**Comment by shuoli84** [comment] 2015-07-27 12:56
Change stock from struct to class.

**Comment by shuoli84** [comment] 2015-07-27 18:51
Here is what I found:

In CombineLatest+arity.swift, in run(). The setLatestValue for observer2, self.latestElement2 = e. If that one executed, then the lock (NSRecursiveLock) will be corrupted. I tried my best to dig into assembly code, but too late to dig deeper. Refer to the screen shot. The first po is good, the second one is broken. 

![screen shot 2015-07-28 at 2 46 51 am](https://cloud.githubusercontent.com/assets/3402035/8914658/19e18734-34d3-11e5-910f-3d1d701f69e8.png)

**Comment by kzaher** [comment] 2015-07-27 19:40
Hi, 
I’m sending you zip file with test project I’ve set up on your email shuoli84@gmail.com.

It has latest version of RxSwift source files included inside the project and deployment target set to 7.0.

When I was testing this I was using

Version 6.4 (6E35b)
OSX 10.10.4 (14E46)
I’m testing on iPhone 5 - iOS 7 simulator (7.1 - 11D167)

It looks like it worked fine even when I’ve changed struct to class

If you could tell me does that crash for you that would be great.

If it doesn’t, maybe you could add changes that crash it and send that project so I can see does it crash for me also.

Really appreciate your help with this.

Kruno

**Comment by kzaher** [comment] 2015-07-27 19:45
That crash is really confusing. I have experienced similar crashes that were caused with swift compiler wrong compiling curried functions.

Are you maybe using curried functions somewhere in your code. I've heard that issue was fixed, but it still freaks me out so I just continue to use lambdas instead of curried functions.

Do you have turned on zombie objects. That could help discover the root cause sooner.

<img width="1012" alt="screen shot 2015-07-27 at 21 43 36" src="https://cloud.githubusercontent.com/assets/1641148/8915968/96f41bd6-34a8-11e5-9af8-0abdd4449a8a.png">

I'm not sure how it can access corrupted memory because I'm not using unowned or even weak for that matter.

Hope you can tell me what are the results of running that example project that I've sent to you that has the code you've sent me, so that should hopefully clear things up.

**Comment by shuoli84** [comment] 2015-07-27 23:55
I already enabled zombie object, but it doesn't help too much. 
I tried the project, it crashed under iphone 5s 7.111D167, but not under iphone 5. XCode version and osx version are same as yours. 
Try run it under iphone 5s 7.1?

**Comment by shuoli84** [comment] 2015-07-28 00:00
iphone 5 simulator use build arc as i386, iphone 5s using x86_64, I guess the compiler for x86-64 had a bug causing the problem.

**Comment by shuoli84** [comment] 2015-07-28 00:41
![screen shot 2015-07-28 at 8 40 05 am](https://cloud.githubusercontent.com/assets/3402035/8921097/4afdc702-3504-11e5-86b9-7b1df2e9fa21.png)

The lock is modified by this libswiftCore.dylib VlaueWitnesses thing assign with Take.

**Comment by shuoli84** [comment] 2015-07-28 01:44
Under iphone 5, the assignWithTake won't be called, but under iphone 5s(x86), it is called. Which means the compiler treat NSRecursiveLock differently.

**Comment by shuoli84** [comment] 2015-07-28 10:49
I believe it is a compiler bug. One cause that I found is: The CombineLatestSink class, the memory allocated for it is not the size that it requires. 

I added some bounds values, so the size may not the same as your project.
```
(lldb) malloc_info 0x00007fc9e171ecf0
0x00007fc9e171ecf0: malloc(   128) -> 0x7fc9e171ecf0 _TtC14RxCocoaPodTest19CombineLatestSink2_00007FC9E3017050._TtC14RxCocoaPodTest17CombineLatestSink00007FC9E171E130._TtC14RxCocoaPodTest4Sink00007FC9E171DBD0.SwiftObject.magic_isa

(lldb) malloc_info 0x00007fc9e171ed70
0x00007fc9e171ed70: malloc(    48) -> 0x7fc9e171ed70
```
So part of the object is overwritten by some other logic, which caused very weird crash.

**Comment by kzaher** [comment] 2015-07-28 11:37
Huh, you are right. It crashes on iOS 7.1 5S consistently for me also, but not on any other combinations of platform/os :(

Including 5S on 8.4

It also looks to me this is a compiler/swift framework bug :(

I'm not sure I can do anything here :(

**Comment by kzaher** [comment] 2015-07-28 11:38
Awesome investigation @shuoli84 
:bow:

**Comment by shuoli84** [comment] 2015-07-28 15:58
I am trying to find why the compiler couldn't calculate the size correctly. I believe there should be a workaround.

**Comment by shuoli84** [comment] 2015-07-28 17:26
@kzaher The reason I find is: If we mix the class and enum as E1 and E2 for combineLatest, then it has problem to get the right size. If both are Enum or classes, it will be fine. 
How to fix: Use RxBox to wrap the E1 and E2 to make them class, then this will workaround the bug.

**Comment by croccio** [comment] 2015-07-28 18:44
can you explain hoe use rxswift for is? i have to copy manually lib in my project?

**Comment by shuoli84** [comment] 2015-07-29 02:38
@croccio Same here. Just copy the files.

**Comment by kzaher** [comment] 2015-07-29 09:44
I've made some additional instructions https://github.com/kzaher/RxSwift/issues/74.

Since we are getting more questions about iOS 7 support recently, I'll try to do something nicer about it then that.

**Comment by kzaher** [comment] 2015-08-03 06:30
I've added official support for iOS 7 in latest release and explanation how to install RxSwift on iOS 7.

Closing this issue.

**Closed by kzaher** 2015-08-03 06:30 UTC
