### ISSUE TITLE
tryMap & flatMap operators

### ISSUE THREAD

**Issue by alcarvalho** [kzaher/RxSwift#33] opened 2015-06-10 19:47 UTC
ReactiveCocoa has an operator which is called `tryMap` is not the best name but I think we should have something similar on RxSwift.

On RxJava, the `map` itself is able to handle any runtime errors and just send an error event in case something throws inside the `map` operator. That would be the nicest way to have it. And maybe with Swift 2 will be able to.

But for now, how can we approach that?

Another operator that's really, really missing is a flatMap, don't you think?

I guess I could help with that, but I am creating this issue to discuss before.

**Comment by kzaher** [comment] 2015-06-10 20:04
Haha, 
I have good sense for timing :)

`flatMap` will be ported in a few days, and it's in the process of porting.

For functions that can accept selector, there is usually *orDie overload that returns `RxResult`. This is documented little confusing right now in README.md. I'll fix that.

The orDie suffix was chosen as a explanation what will happen if function fails. Entire sink chain will be disposed. Maybe I should reconsider the wording in next 2.0 version.

So in case of `map`, you have `mapOrDie` (you can return `success(value)` or `failure(error)` from this one).

You have `filter` (that can never fail), and `filterOrDie` that can return error.

...

**Comment by alcarvalho** [comment] 2015-06-10 20:07
That's great news! :+1: 
And thank you for the explanation on the orDie operators. :smile:

**Comment by kzaher** [comment] 2015-06-10 20:15
I usually learn where I've messed something when people are confused, so I'm solving one confusion at a time :)

Feel free to let me know if there are other pain points.

**Comment by kzaher** [comment] 2015-06-12 20:10
FYI, flatMap has entered develop branch, and he brought two friends with him :)

It will be released end week with other improvements.

**Comment by alcarvalho** [comment] 2015-06-12 20:13
Great, @kzaher! Thank you...

I was thinking about the OrDie functions. Maybe it would be clearer if they were called something like 'assertMap' as a prefix. Or even "mapOrError". 

I have to confess I was afraid to use these "OrDie" functions at first because of their names, hahaha...

**Comment by kzaher** [comment] 2015-06-12 20:15
Then I'm glad they are working as designed and scare people :) That was my actual intention ;)

Maybe I should rename `catch` to `resurrect` :)))

**Comment by alcarvalho** [comment] 2015-06-12 20:17
That would be awesome! :stuck_out_tongue_closed_eyes:

**Comment by kzaher** [comment] 2015-06-19 08:55
Hi,
so `flatMap` has entered the building :)
As for `orDie` suffix, I don't think it's ideal, but don't think it's horrible either :)

I think that your other suggestion you've made on Slack `orFail` could be maybe better then `orDie`, but I'll need to think about if and when to make those changes.

For now, I'll close this issue since `flatMap` is added to `RxSwift`, but you can open new one with `orFail` suggestion if you like.

**Closed by kzaher** 2015-06-19 08:55 UTC
Labels: enhancement, question
